# Default values for portainer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: portainer/portainer-ce
  tag: 2.19.0

imagePullSecrets: []

nodeSelector: {}

serviceAccount:
  annotations: {}
  name: portainer-sa-clusteradmin

service:
  # Set the httpNodePort and edgeNodePort only if the type is NodePort
  # For Ingress, set the type to be ClusterIP and set ingress.enabled to true
  # For Cloud Providers, set the type to be LoadBalancer
  type: ClusterIP
  httpPort: 9000
  httpsPort: 9443
  httpNodePort: 30777
  httpsNodePort: 30779
  edgePort: 8000
  edgeNodePort: 30776
  annotations: {}

feature:
  flags: ""

resources: {}

persistence:
  enabled: true
  size: "5Gi"
